select * from Customer
select * from prod_cat_info
select * from Transactions


--1. What is the total number of rows in each of the 3 tables in the database? 

select count(*) as total_customers from customer

select count(*) as total_info from prod_cat_info

select count(*) as total_transaction from transactions

--2. What is the total number of transactions that have a return? 
 select * from Transactions
         where total_amt < 0

 select count(*) 
         from Transactions as total_return
         where total_amt < 0


--3. As you would have noticed, the dates provided across the datasets are not in a 
--correct format. As first steps, pls convert the date variables into valid date formats 
--before proceeding ahead. 

update Transactions
   set tran_date = TRY_CONVERT(date,tran_date,103)

/*4. What is the time range of the transaction data available for analysis? Show the 
output in number of days, months and years simultaneously in different columns. */

/*select DAY(tran_date) as days,
     --  YEAR(tran_date) as years,
       month(tran_date) as months
       from Transactions*/

 select min(tran_date) as start_date,
       max(tran_date) as end_date,
       DATEDIFF(day,min(tran_date)),
       max(tran_date) as total_days,
       DATEDIFF(month,min(tran_date))
       from Transactions



/*5. Which product category does the sub-category “DIY” belong to? */
select * from prod_cat_info
     where prod_subcat='div'


   ---  DATA ANALYSIS 
/*1. Which channel is most frequently used for transactions? */
select * from Transactions

select store_type,
       count(*) as total_tansaction
       from Transactions
       group by Store_type
       order by  count(*) desc


/*2. What is the count of Male and Female customers in the database? */

select * from customer

select gender,
count(gender) as total_gender
from customer
group by gender

/*3. From which city do we have the maximum number of customers and how many? */

select city_code, count(*) as total_customers
from Customer c
group by city_code
order by count(*) desc

   
/*4. How many sub-categories are there under the Books category? */

select prod_cat ,count( distinct prod_subcat)
        as total_subcategory
        from prod_cat_info
        where prod_cat ='books'
        group by prod_cat

--5. What is the maximum quantity of products ever ordered? 

    select max(qty) as total_quantity
    from Transactions

--6. What is the net total revenue generated in categories Electronics and Books? 

select p.prod_cat, SUM(total_amt) as revenue
        from prod_cat_info p
        inner join Transactions t
        on t.prod_cat_code=p.prod_cat_code
        where p.prod_cat in ('Electronics','Books')
        group by p.prod_cat

--7. How many customers have >10 transactions with us, excluding returns? 

select cust_id,count(cust_id) as excluding_return
      from Transactions
      where total_amt>0
      group by cust_id
      having count(cust_id) >10

/*8. What is the combined revenue earned from the “Electronics” & “Clothing” 
categories, from “Flagship stores”? */
select * from Transactions

select sum(t.total_amt) as total_revenue
         from Transactions t
         join prod_cat_info p
         on p.prod_cat_code=t.prod_cat_code
         where p.prod_cat in ('Electronics','Clothing') and t.Store_type='flagship store';

/*9. What is the total revenue generated from “Male” customers in “Electronics” 
category? Output should display total revenue by prod sub-cat.*/ 

select p.prod_subcat,sum(t.total_amt) as total_revenue
   from Transactions t
   join customer c 
   on c.customer_Id=t.cust_id
   join prod_cat_info p on t.prod_cat_code=p.prod_cat_code
   where c.Gender='m' and p.prod_cat='electronics'
   group by p.prod_subcat


/*10.What is percentage of sales and returns by product sub category; display only top 
5 sub categories in terms of sales?*/

WITH SalesReturns AS (
    SELECT 
        pci.prod_subcat,
        SUM(CASE WHEN t.Qty > 0 THEN t.total_amt ELSE 0 END) AS sales_amt,
        SUM(CASE WHEN t.Qty < 0 THEN ABS(t.total_amt) ELSE 0 END) AS return_amt
    FROM Transactions t
    JOIN prod_cat_info pci ON t.prod_cat_code = pci.prod_cat_code
    GROUP BY pci.prod_subcat
),
Totals AS (
    SELECT SUM(sales_amt) AS total_sales FROM SalesReturns
)
SELECT TOP 5
    sr.prod_subcat,
    sr.sales_amt,
    ROUND(100.0 * sr.sales_amt / t.total_sales, 2) AS sales_percentage,
    sr.return_amt,
    ROUND(100.0 * sr.return_amt / NULLIF(sr.sales_amt, 0), 2) AS return_percentage
FROM SalesReturns sr, Totals t
ORDER BY sr.sales_amt DESC;

/*11. For all customers aged between 25 to 35 years find what is the net total revenue 
generated by these consumers in last 30 days of transactions from max transaction 
date available in the data?*/ 

WITH AgeFiltered AS (
    SELECT customer_Id, DATEDIFF(YEAR, DOB, GETDATE()) AS age
    FROM Customer
    WHERE DATEDIFF(YEAR, DOB, GETDATE()) BETWEEN 25 AND 35
),
MaxDate AS (
    SELECT MAX(tran_date) AS max_tran_date FROM Transactions
),
Last30Days AS (
    SELECT t.*
    FROM Transactions t, MaxDate m
    WHERE t.tran_date >= DATEADD(DAY, -30, m.max_tran_date)
      AND t.Qty > 0
)
SELECT SUM(l.total_amt) AS net_revenue_last_30_days
FROM Last30Days l
JOIN AgeFiltered a ON l.cust_id = a.customer_Id;

/*12.Which product category has seen the max value of returns in the last 3 months of 
transactions? */

WITH Last3Months AS (
    SELECT t.*, pci.prod_cat
    FROM Transactions t
    JOIN prod_cat_info pci ON t.prod_cat_code = pci.prod_cat_code
    WHERE t.Qty < 0
      AND t.tran_date >= DATEADD(MONTH, -3, (SELECT MAX(tran_date) FROM Transactions))
)
SELECT TOP 1 prod_cat, SUM(ABS(total_amt)) AS return_value
FROM Last3Months
GROUP BY prod_cat
ORDER BY return_value DESC;

/*13.Which store-type sells the maximum products; by value of sales amount and by 
quantity sold?*/ 

-- By Sales Amount
SELECT TOP 1 Store_type, SUM(total_amt) AS total_sales
FROM Transactions
WHERE Qty > 0
GROUP BY Store_type
ORDER BY total_sales DESC;

-- By Quantity
SELECT TOP 1 Store_type, SUM(Qty) AS total_qty
FROM Transactions
WHERE Qty > 0
GROUP BY Store_type
ORDER BY total_qty DESC

--14.What are the categories for which average revenue is above the overall average. 

WITH CatRevenue AS (
    SELECT pci.prod_cat, AVG(t.total_amt) AS avg_revenue
    FROM Transactions t
    JOIN prod_cat_info pci ON t.prod_cat_code = pci.prod_cat_code
    WHERE t.Qty > 0
    GROUP BY pci.prod_cat
),
OverallAvg AS (
    SELECT AVG(total_amt) AS overall_avg FROM Transactions WHERE Qty > 0
)
SELECT cr.prod_cat, cr.avg_revenue
FROM CatRevenue cr, OverallAvg oa
WHERE cr.avg_revenue > oa.overall_avg

/*15. Find the average and total revenue by each subcategory for the categories which 
are among top 5 categories in terms of quantity sold.*/ 

WITH Top5Cats AS (
    SELECT TOP 5 pci.prod_cat
    FROM Transactions t
    JOIN prod_cat_info pci ON t.prod_cat_code = pci.prod_cat_code
    WHERE t.Qty > 0
    GROUP BY pci.prod_cat
    ORDER BY SUM(t.Qty) DESC
),
SubCatRevenue AS (
    SELECT 
        pci.prod_cat,
        pci.prod_subcat,
        SUM(t.total_amt) AS total_revenue,
        AVG(t.total_amt) AS avg_revenue,
        SUM(t.Qty) AS total_qty
    FROM Transactions t
    JOIN prod_cat_info pci ON t.prod_cat_code = pci.prod_cat_code
    WHERE t.Qty > 0 AND pci.prod_cat IN (SELECT prod_cat FROM Top5Cats)
    GROUP BY pci.prod_cat, pci.prod_subcat
)
SELECT prod_cat, prod_subcat, total_revenue, avg_revenue
FROM SubCatRevenue
ORDER BY prod_cat, total_revenue DESC